### ISSUE TITLE
Uncaught Exception in Web SDK Extension

### ISSUE THREAD

**Issue by jbradley-evo** [adobe/reactor-extension-alloy#346]
The following error popped up in the console:

```
Uncaught (in promise) TypeError: [alloy] [Identity] An error occurred while executing the getIdentity command.
Caused by: [Identity] An error occurred while executing the onBeforeRequest lifecycle hook.
Caused by: o.split is not a function
```

This kept the page from working. Investigation showed the root of the problem was the adobe_mc parameter had been appended to the URL twice (by accident). The code that parses the parameter value does not do a type check after getting the parameter, and when there are more than one instance of a parameter it is represented by an array instead of a string. The code attempts to do a split() operation, but since the type is Array the exception is thrown.

The extension needs to be updated to check the type and take appropriate action if it is an Array and not a String.

We are correcting the problem that caused the parameter to be added twice, but the extension should have better error handling.

To reproduce, create a link with the adobe_mc parameter duplicated and observe the behavior on the destination site.

Here is a screenshot of the code that threw the exception:
![Extension Code Extract](https://github.com/adobe/reactor-extension-alloy/assets/50153324/e27f2a41-640e-42b6-8fba-235774ec9a87)

This is the value of "o".  Note that it is an Array and not a String as the code is expecting
![adobe_mc Param as Array](https://github.com/adobe/reactor-extension-alloy/assets/50153324/19006d4b-ee38-45a7-877d-1be2b07aacd4)

**Comment by jonsnyder** [comment]
Thanks for the report. Yes this error is not ideal. Logged as https://jira.corp.adobe.com/browse/PDCL-11037
